# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: task_service/task_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'task_service/task_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ftask_service/task_service.proto\x12\x0ctask_service\"\xa8\x01\n\x11RedundancyOptions\x12\x12\n\nmin_quorum\x18\x01 \x01(\x05\x12\x17\n\x0ftarget_nresults\x18\x02 \x01(\x05\x12\x19\n\x11max_error_results\x18\x03 \x01(\x05\x12\x19\n\x11max_total_results\x18\x04 \x01(\x05\x12\x1b\n\x13max_success_results\x18\x05 \x01(\x05\x12\x13\n\x0b\x64\x65lay_bound\x18\x06 \x01(\x03\"\xa8\x01\n\x11\x43reateTaskRequest\x12\x0e\n\x06\x66lavor\x18\x01 \x01(\t\x12\x11\n\tcall_spec\x18\x02 \x01(\x0c\x12\x17\n\x0finit_valid_func\x18\x03 \x01(\x0c\x12\x1a\n\x12\x63ompare_valid_func\x18\x04 \x01(\x0c\x12;\n\x12redundancy_options\x18\x05 \x01(\x0b\x32\x1f.task_service.RedundancyOptions\"%\n\x12\x43reateTaskResponse\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"\"\n\x0fPollTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"\xac\x01\n\x10PollTaskResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12-\n\x0btask_status\x18\x02 \x01(\x0e\x32\x18.task_service.TaskStatus\x12\x31\n\rresult_status\x18\x03 \x01(\x0e\x32\x1a.task_service.ResultStatus\x12\x10\n\x08returned\x18\x04 \x01(\x0c\x12\x15\n\rerror_message\x18\x05 \x01(\t*4\n\nTaskStatus\x12\x0b\n\x07PENDING\x10\x00\x12\x0b\n\x07RUNNING\x10\x01\x12\x0c\n\x08\x46INISHED\x10\x02*=\n\x0cResultStatus\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0e\n\nUSER_ERROR\x10\x01\x12\x10\n\x0cSYSTEM_ERROR\x10\x02\x32\xa9\x01\n\x0bTaskService\x12O\n\nCreateTask\x12\x1f.task_service.CreateTaskRequest\x1a .task_service.CreateTaskResponse\x12I\n\x08PollTask\x12\x1d.task_service.PollTaskRequest\x1a\x1e.task_service.PollTaskResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'task_service.task_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASKSTATUS']._serialized_start=641
  _globals['_TASKSTATUS']._serialized_end=693
  _globals['_RESULTSTATUS']._serialized_start=695
  _globals['_RESULTSTATUS']._serialized_end=756
  _globals['_REDUNDANCYOPTIONS']._serialized_start=50
  _globals['_REDUNDANCYOPTIONS']._serialized_end=218
  _globals['_CREATETASKREQUEST']._serialized_start=221
  _globals['_CREATETASKREQUEST']._serialized_end=389
  _globals['_CREATETASKRESPONSE']._serialized_start=391
  _globals['_CREATETASKRESPONSE']._serialized_end=428
  _globals['_POLLTASKREQUEST']._serialized_start=430
  _globals['_POLLTASKREQUEST']._serialized_end=464
  _globals['_POLLTASKRESPONSE']._serialized_start=467
  _globals['_POLLTASKRESPONSE']._serialized_end=639
  _globals['_TASKSERVICE']._serialized_start=759
  _globals['_TASKSERVICE']._serialized_end=928
# @@protoc_insertion_point(module_scope)
